name: "CI (Integração Continua): Main Workflow"

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
      branches: [ "main" ]
  pull_request:
    types: [opened, synchronize]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Installation
        run: yarn install
      - name: Run Linter
        run: yarn lint
  preview:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Installation
        run: yarn install
      - name: Run preview deploy
        run: yarn deploy:preview    
  test:e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 16.15.0
          cache: 'yarn'  
      - name: Cypress
       uses: cypress-io/github-action@v4
       with: 
          browser: chrome
      - name: Run Installation
        run: yarn install
      - name: Run Linter
        run: yarn test:e2e      
